// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: analysis.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisService_GetAnalysis_FullMethodName    = "/cryptohub.AnalysisService/GetAnalysis"
	AnalysisService_StreamAnalysis_FullMethodName = "/cryptohub.AnalysisService/StreamAnalysis"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalysisService provides AI-powered market analysis.
type AnalysisServiceClient interface {
	// GetAnalysis returns AI analysis for a given symbol and timeframe.
	GetAnalysis(ctx context.Context, in *AnalysisReq, opts ...grpc.CallOption) (*AnalysisResp, error)
	// StreamAnalysis provides streaming analysis updates.
	StreamAnalysis(ctx context.Context, in *AnalysisReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalysisResp], error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) GetAnalysis(ctx context.Context, in *AnalysisReq, opts ...grpc.CallOption) (*AnalysisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResp)
	err := c.cc.Invoke(ctx, AnalysisService_GetAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) StreamAnalysis(ctx context.Context, in *AnalysisReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalysisResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalysisService_ServiceDesc.Streams[0], AnalysisService_StreamAnalysis_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalysisReq, AnalysisResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_StreamAnalysisClient = grpc.ServerStreamingClient[AnalysisResp]

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
//
// AnalysisService provides AI-powered market analysis.
type AnalysisServiceServer interface {
	// GetAnalysis returns AI analysis for a given symbol and timeframe.
	GetAnalysis(context.Context, *AnalysisReq) (*AnalysisResp, error)
	// StreamAnalysis provides streaming analysis updates.
	StreamAnalysis(*AnalysisReq, grpc.ServerStreamingServer[AnalysisResp]) error
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) GetAnalysis(context.Context, *AnalysisReq) (*AnalysisResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysis not implemented")
}
func (UnimplementedAnalysisServiceServer) StreamAnalysis(*AnalysisReq, grpc.ServerStreamingServer[AnalysisResp]) error {
	return status.Error(codes.Unimplemented, "method StreamAnalysis not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_GetAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetAnalysis(ctx, req.(*AnalysisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_StreamAnalysis_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalysisReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalysisServiceServer).StreamAnalysis(m, &grpc.GenericServerStream[AnalysisReq, AnalysisResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_StreamAnalysisServer = grpc.ServerStreamingServer[AnalysisResp]

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptohub.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnalysis",
			Handler:    _AnalysisService_GetAnalysis_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAnalysis",
			Handler:       _AnalysisService_StreamAnalysis_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "analysis.proto",
}
