// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analysis.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Indicators    []string               `protobuf:"bytes,3,rep,name=indicators,proto3" json:"indicators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisReq) Reset() {
	*x = AnalysisReq{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisReq) ProtoMessage() {}

func (x *AnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisReq.ProtoReflect.Descriptor instead.
func (*AnalysisReq) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalysisReq) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *AnalysisReq) GetIndicators() []string {
	if x != nil {
		return x.Indicators
	}
	return nil
}

type AnalysisResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Signal          string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`           // "buy", "sell", "neutral"
	Confidence      float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 – 1.0
	Summary         string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	IndicatorValues map[string]float64     `protobuf:"bytes,5,rep,name=indicator_values,json=indicatorValues,proto3" json:"indicator_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Timestamp       string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalysisResp) Reset() {
	*x = AnalysisResp{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResp) ProtoMessage() {}

func (x *AnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResp.ProtoReflect.Descriptor instead.
func (*AnalysisResp) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResp) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalysisResp) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *AnalysisResp) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalysisResp) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisResp) GetIndicatorValues() map[string]float64 {
	if x != nil {
		return x.IndicatorValues
	}
	return nil
}

func (x *AnalysisResp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_rawDesc = "" +
	"\n" +
	"\x0eanalysis.proto\x12\tcryptohub\"c\n" +
	"\vAnalysisReq\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x1e\n" +
	"\n" +
	"indicators\x18\x03 \x03(\tR\n" +
	"indicators\"\xb3\x02\n" +
	"\fAnalysisResp\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12W\n" +
	"\x10indicator_values\x18\x05 \x03(\v2,.cryptohub.AnalysisResp.IndicatorValuesEntryR\x0findicatorValues\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x1aB\n" +
	"\x14IndicatorValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\x96\x01\n" +
	"\x0fAnalysisService\x12>\n" +
	"\vGetAnalysis\x12\x16.cryptohub.AnalysisReq\x1a\x17.cryptohub.AnalysisResp\x12C\n" +
	"\x0eStreamAnalysis\x12\x16.cryptohub.AnalysisReq\x1a\x17.cryptohub.AnalysisResp0\x01B7Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pbb\x06proto3"

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData []byte
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_analysis_proto_goTypes = []any{
	(*AnalysisReq)(nil),  // 0: cryptohub.AnalysisReq
	(*AnalysisResp)(nil), // 1: cryptohub.AnalysisResp
	nil,                  // 2: cryptohub.AnalysisResp.IndicatorValuesEntry
}
var file_analysis_proto_depIdxs = []int32{
	2, // 0: cryptohub.AnalysisResp.indicator_values:type_name -> cryptohub.AnalysisResp.IndicatorValuesEntry
	0, // 1: cryptohub.AnalysisService.GetAnalysis:input_type -> cryptohub.AnalysisReq
	0, // 2: cryptohub.AnalysisService.StreamAnalysis:input_type -> cryptohub.AnalysisReq
	1, // 3: cryptohub.AnalysisService.GetAnalysis:output_type -> cryptohub.AnalysisResp
	1, // 4: cryptohub.AnalysisService.StreamAnalysis:output_type -> cryptohub.AnalysisResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
