// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: indicator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndicatorParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g. "SMA", "RSI", "MACD"
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorParam) Reset() {
	*x = IndicatorParam{}
	mi := &file_indicator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorParam) ProtoMessage() {}

func (x *IndicatorParam) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorParam.ProtoReflect.Descriptor instead.
func (*IndicatorParam) Descriptor() ([]byte, []int) {
	return file_indicator_proto_rawDescGZIP(), []int{0}
}

func (x *IndicatorParam) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IndicatorParam) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *IndicatorParam) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type IndicatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"` // e.g. "1H", "4H", "1D"
	Indicators    []*IndicatorParam      `protobuf:"bytes,3,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // number of data points
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorReq) Reset() {
	*x = IndicatorReq{}
	mi := &file_indicator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorReq) ProtoMessage() {}

func (x *IndicatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorReq.ProtoReflect.Descriptor instead.
func (*IndicatorReq) Descriptor() ([]byte, []int) {
	return file_indicator_proto_rawDescGZIP(), []int{1}
}

func (x *IndicatorReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IndicatorReq) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *IndicatorReq) GetIndicators() []*IndicatorParam {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *IndicatorReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type IndicatorValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorValue) Reset() {
	*x = IndicatorValue{}
	mi := &file_indicator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorValue) ProtoMessage() {}

func (x *IndicatorValue) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorValue.ProtoReflect.Descriptor instead.
func (*IndicatorValue) Descriptor() ([]byte, []int) {
	return file_indicator_proto_rawDescGZIP(), []int{2}
}

func (x *IndicatorValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IndicatorValue) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *IndicatorValue) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndicatorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Indicators    []*IndicatorValue      `protobuf:"bytes,2,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorResp) Reset() {
	*x = IndicatorResp{}
	mi := &file_indicator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorResp) ProtoMessage() {}

func (x *IndicatorResp) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorResp.ProtoReflect.Descriptor instead.
func (*IndicatorResp) Descriptor() ([]byte, []int) {
	return file_indicator_proto_rawDescGZIP(), []int{3}
}

func (x *IndicatorResp) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IndicatorResp) GetIndicators() []*IndicatorValue {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *IndicatorResp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type BatchIndicatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*IndicatorReq        `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIndicatorReq) Reset() {
	*x = BatchIndicatorReq{}
	mi := &file_indicator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIndicatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIndicatorReq) ProtoMessage() {}

func (x *BatchIndicatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIndicatorReq.ProtoReflect.Descriptor instead.
func (*BatchIndicatorReq) Descriptor() ([]byte, []int) {
	return file_indicator_proto_rawDescGZIP(), []int{4}
}

func (x *BatchIndicatorReq) GetRequests() []*IndicatorReq {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchIndicatorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*IndicatorResp       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIndicatorResp) Reset() {
	*x = BatchIndicatorResp{}
	mi := &file_indicator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIndicatorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIndicatorResp) ProtoMessage() {}

func (x *BatchIndicatorResp) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIndicatorResp.ProtoReflect.Descriptor instead.
func (*BatchIndicatorResp) Descriptor() ([]byte, []int) {
	return file_indicator_proto_rawDescGZIP(), []int{5}
}

func (x *BatchIndicatorResp) GetResults() []*IndicatorResp {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_indicator_proto protoreflect.FileDescriptor

const file_indicator_proto_rawDesc = "" +
	"\n" +
	"\x0findicator.proto\x12\tcryptohub\"\xb2\x01\n" +
	"\x0eIndicatorParam\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\x12:\n" +
	"\x05extra\x18\x03 \x03(\v2$.cryptohub.IndicatorParam.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\fIndicatorReq\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x129\n" +
	"\n" +
	"indicators\x18\x03 \x03(\v2\x19.cryptohub.IndicatorParamR\n" +
	"indicators\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xbe\x01\n" +
	"\x0eIndicatorValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\x12C\n" +
	"\bmetadata\x18\x03 \x03(\v2'.cryptohub.IndicatorValue.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\rIndicatorResp\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x129\n" +
	"\n" +
	"indicators\x18\x02 \x03(\v2\x19.cryptohub.IndicatorValueR\n" +
	"indicators\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"H\n" +
	"\x11BatchIndicatorReq\x123\n" +
	"\brequests\x18\x01 \x03(\v2\x17.cryptohub.IndicatorReqR\brequests\"H\n" +
	"\x12BatchIndicatorResp\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.cryptohub.IndicatorRespR\aresults2\xa1\x01\n" +
	"\x10IndicatorService\x12>\n" +
	"\tCalculate\x12\x17.cryptohub.IndicatorReq\x1a\x18.cryptohub.IndicatorResp\x12M\n" +
	"\x0eBatchCalculate\x12\x1c.cryptohub.BatchIndicatorReq\x1a\x1d.cryptohub.BatchIndicatorRespB7Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pbb\x06proto3"

var (
	file_indicator_proto_rawDescOnce sync.Once
	file_indicator_proto_rawDescData []byte
)

func file_indicator_proto_rawDescGZIP() []byte {
	file_indicator_proto_rawDescOnce.Do(func() {
		file_indicator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indicator_proto_rawDesc), len(file_indicator_proto_rawDesc)))
	})
	return file_indicator_proto_rawDescData
}

var file_indicator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_indicator_proto_goTypes = []any{
	(*IndicatorParam)(nil),     // 0: cryptohub.IndicatorParam
	(*IndicatorReq)(nil),       // 1: cryptohub.IndicatorReq
	(*IndicatorValue)(nil),     // 2: cryptohub.IndicatorValue
	(*IndicatorResp)(nil),      // 3: cryptohub.IndicatorResp
	(*BatchIndicatorReq)(nil),  // 4: cryptohub.BatchIndicatorReq
	(*BatchIndicatorResp)(nil), // 5: cryptohub.BatchIndicatorResp
	nil,                        // 6: cryptohub.IndicatorParam.ExtraEntry
	nil,                        // 7: cryptohub.IndicatorValue.MetadataEntry
}
var file_indicator_proto_depIdxs = []int32{
	6, // 0: cryptohub.IndicatorParam.extra:type_name -> cryptohub.IndicatorParam.ExtraEntry
	0, // 1: cryptohub.IndicatorReq.indicators:type_name -> cryptohub.IndicatorParam
	7, // 2: cryptohub.IndicatorValue.metadata:type_name -> cryptohub.IndicatorValue.MetadataEntry
	2, // 3: cryptohub.IndicatorResp.indicators:type_name -> cryptohub.IndicatorValue
	1, // 4: cryptohub.BatchIndicatorReq.requests:type_name -> cryptohub.IndicatorReq
	3, // 5: cryptohub.BatchIndicatorResp.results:type_name -> cryptohub.IndicatorResp
	1, // 6: cryptohub.IndicatorService.Calculate:input_type -> cryptohub.IndicatorReq
	4, // 7: cryptohub.IndicatorService.BatchCalculate:input_type -> cryptohub.BatchIndicatorReq
	3, // 8: cryptohub.IndicatorService.Calculate:output_type -> cryptohub.IndicatorResp
	5, // 9: cryptohub.IndicatorService.BatchCalculate:output_type -> cryptohub.BatchIndicatorResp
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_indicator_proto_init() }
func file_indicator_proto_init() {
	if File_indicator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indicator_proto_rawDesc), len(file_indicator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indicator_proto_goTypes,
		DependencyIndexes: file_indicator_proto_depIdxs,
		MessageInfos:      file_indicator_proto_msgTypes,
	}.Build()
	File_indicator_proto = out.File
	file_indicator_proto_goTypes = nil
	file_indicator_proto_depIdxs = nil
}
