// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: indicator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndicatorService_Calculate_FullMethodName      = "/cryptohub.IndicatorService/Calculate"
	IndicatorService_BatchCalculate_FullMethodName = "/cryptohub.IndicatorService/BatchCalculate"
)

// IndicatorServiceClient is the client API for IndicatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IndicatorService calculates technical indicators.
type IndicatorServiceClient interface {
	// Calculate computes requested indicators for a symbol.
	Calculate(ctx context.Context, in *IndicatorReq, opts ...grpc.CallOption) (*IndicatorResp, error)
	// BatchCalculate computes indicators for multiple symbols.
	BatchCalculate(ctx context.Context, in *BatchIndicatorReq, opts ...grpc.CallOption) (*BatchIndicatorResp, error)
}

type indicatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndicatorServiceClient(cc grpc.ClientConnInterface) IndicatorServiceClient {
	return &indicatorServiceClient{cc}
}

func (c *indicatorServiceClient) Calculate(ctx context.Context, in *IndicatorReq, opts ...grpc.CallOption) (*IndicatorResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndicatorResp)
	err := c.cc.Invoke(ctx, IndicatorService_Calculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indicatorServiceClient) BatchCalculate(ctx context.Context, in *BatchIndicatorReq, opts ...grpc.CallOption) (*BatchIndicatorResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchIndicatorResp)
	err := c.cc.Invoke(ctx, IndicatorService_BatchCalculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndicatorServiceServer is the server API for IndicatorService service.
// All implementations must embed UnimplementedIndicatorServiceServer
// for forward compatibility.
//
// IndicatorService calculates technical indicators.
type IndicatorServiceServer interface {
	// Calculate computes requested indicators for a symbol.
	Calculate(context.Context, *IndicatorReq) (*IndicatorResp, error)
	// BatchCalculate computes indicators for multiple symbols.
	BatchCalculate(context.Context, *BatchIndicatorReq) (*BatchIndicatorResp, error)
	mustEmbedUnimplementedIndicatorServiceServer()
}

// UnimplementedIndicatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndicatorServiceServer struct{}

func (UnimplementedIndicatorServiceServer) Calculate(context.Context, *IndicatorReq) (*IndicatorResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedIndicatorServiceServer) BatchCalculate(context.Context, *BatchIndicatorReq) (*BatchIndicatorResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCalculate not implemented")
}
func (UnimplementedIndicatorServiceServer) mustEmbedUnimplementedIndicatorServiceServer() {}
func (UnimplementedIndicatorServiceServer) testEmbeddedByValue()                          {}

// UnsafeIndicatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndicatorServiceServer will
// result in compilation errors.
type UnsafeIndicatorServiceServer interface {
	mustEmbedUnimplementedIndicatorServiceServer()
}

func RegisterIndicatorServiceServer(s grpc.ServiceRegistrar, srv IndicatorServiceServer) {
	// If the following call panics, it indicates UnimplementedIndicatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndicatorService_ServiceDesc, srv)
}

func _IndicatorService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndicatorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndicatorServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndicatorService_Calculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndicatorServiceServer).Calculate(ctx, req.(*IndicatorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndicatorService_BatchCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIndicatorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndicatorServiceServer).BatchCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndicatorService_BatchCalculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndicatorServiceServer).BatchCalculate(ctx, req.(*BatchIndicatorReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IndicatorService_ServiceDesc is the grpc.ServiceDesc for IndicatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndicatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptohub.IndicatorService",
	HandlerType: (*IndicatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _IndicatorService_Calculate_Handler,
		},
		{
			MethodName: "BatchCalculate",
			Handler:    _IndicatorService_BatchCalculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indicator.proto",
}
