// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: market.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_GetKlines_FullMethodName       = "/cryptohub.MarketDataService/GetKlines"
	MarketDataService_SubscribeTicker_FullMethodName = "/cryptohub.MarketDataService/SubscribeTicker"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketDataService provides real-time and historical market data.
type MarketDataServiceClient interface {
	// GetKlines returns historical candlestick data.
	GetKlines(ctx context.Context, in *KlineReq, opts ...grpc.CallOption) (*KlineResp, error)
	// SubscribeTicker provides streaming ticker updates.
	SubscribeTicker(ctx context.Context, in *TickerReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TickerUpdate], error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetKlines(ctx context.Context, in *KlineReq, opts ...grpc.CallOption) (*KlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KlineResp)
	err := c.cc.Invoke(ctx, MarketDataService_GetKlines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) SubscribeTicker(ctx context.Context, in *TickerReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TickerUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketDataService_ServiceDesc.Streams[0], MarketDataService_SubscribeTicker_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TickerReq, TickerUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketDataService_SubscribeTickerClient = grpc.ServerStreamingClient[TickerUpdate]

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// MarketDataService provides real-time and historical market data.
type MarketDataServiceServer interface {
	// GetKlines returns historical candlestick data.
	GetKlines(context.Context, *KlineReq) (*KlineResp, error)
	// SubscribeTicker provides streaming ticker updates.
	SubscribeTicker(*TickerReq, grpc.ServerStreamingServer[TickerUpdate]) error
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) GetKlines(context.Context, *KlineReq) (*KlineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKlines not implemented")
}
func (UnimplementedMarketDataServiceServer) SubscribeTicker(*TickerReq, grpc.ServerStreamingServer[TickerUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTicker not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetKlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetKlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetKlines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetKlines(ctx, req.(*KlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_SubscribeTicker_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TickerReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServiceServer).SubscribeTicker(m, &grpc.GenericServerStream[TickerReq, TickerUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketDataService_SubscribeTickerServer = grpc.ServerStreamingServer[TickerUpdate]

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptohub.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKlines",
			Handler:    _MarketDataService_GetKlines_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTicker",
			Handler:       _MarketDataService_SubscribeTicker_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "market.proto",
}
