# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """AnalysisService provides AI-powered market analysis.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalysis = channel.unary_unary(
                '/cryptohub.AnalysisService/GetAnalysis',
                request_serializer=analysis__pb2.AnalysisReq.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisResp.FromString,
                _registered_method=True)
        self.StreamAnalysis = channel.unary_stream(
                '/cryptohub.AnalysisService/StreamAnalysis',
                request_serializer=analysis__pb2.AnalysisReq.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisResp.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """AnalysisService provides AI-powered market analysis.
    """

    def GetAnalysis(self, request, context):
        """GetAnalysis returns AI analysis for a given symbol and timeframe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalysis(self, request, context):
        """StreamAnalysis provides streaming analysis updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysis,
                    request_deserializer=analysis__pb2.AnalysisReq.FromString,
                    response_serializer=analysis__pb2.AnalysisResp.SerializeToString,
            ),
            'StreamAnalysis': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalysis,
                    request_deserializer=analysis__pb2.AnalysisReq.FromString,
                    response_serializer=analysis__pb2.AnalysisResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryptohub.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cryptohub.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """AnalysisService provides AI-powered market analysis.
    """

    @staticmethod
    def GetAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryptohub.AnalysisService/GetAnalysis',
            analysis__pb2.AnalysisReq.SerializeToString,
            analysis__pb2.AnalysisResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cryptohub.AnalysisService/StreamAnalysis',
            analysis__pb2.AnalysisReq.SerializeToString,
            analysis__pb2.AnalysisResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
