# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\tcryptohub\"D\n\x0b\x41nalysisReq\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x12\n\nindicators\x18\x03 \x03(\t\"\xe6\x01\n\x0c\x41nalysisResp\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x46\n\x10indicator_values\x18\x05 \x03(\x0b\x32,.cryptohub.AnalysisResp.IndicatorValuesEntry\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x1a\x36\n\x14IndicatorValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32\x96\x01\n\x0f\x41nalysisService\x12>\n\x0bGetAnalysis\x12\x16.cryptohub.AnalysisReq\x1a\x17.cryptohub.AnalysisResp\x12\x43\n\x0eStreamAnalysis\x12\x16.cryptohub.AnalysisReq\x1a\x17.cryptohub.AnalysisResp0\x01\x42\x37Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pb'
  _globals['_ANALYSISRESP_INDICATORVALUESENTRY']._loaded_options = None
  _globals['_ANALYSISRESP_INDICATORVALUESENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSISREQ']._serialized_start=29
  _globals['_ANALYSISREQ']._serialized_end=97
  _globals['_ANALYSISRESP']._serialized_start=100
  _globals['_ANALYSISRESP']._serialized_end=330
  _globals['_ANALYSISRESP_INDICATORVALUESENTRY']._serialized_start=276
  _globals['_ANALYSISRESP_INDICATORVALUESENTRY']._serialized_end=330
  _globals['_ANALYSISSERVICE']._serialized_start=333
  _globals['_ANALYSISSERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
