# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import indicator_pb2 as indicator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in indicator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndicatorServiceStub(object):
    """IndicatorService calculates technical indicators.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculate = channel.unary_unary(
                '/cryptohub.IndicatorService/Calculate',
                request_serializer=indicator__pb2.IndicatorReq.SerializeToString,
                response_deserializer=indicator__pb2.IndicatorResp.FromString,
                _registered_method=True)
        self.BatchCalculate = channel.unary_unary(
                '/cryptohub.IndicatorService/BatchCalculate',
                request_serializer=indicator__pb2.BatchIndicatorReq.SerializeToString,
                response_deserializer=indicator__pb2.BatchIndicatorResp.FromString,
                _registered_method=True)


class IndicatorServiceServicer(object):
    """IndicatorService calculates technical indicators.
    """

    def Calculate(self, request, context):
        """Calculate computes requested indicators for a symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCalculate(self, request, context):
        """BatchCalculate computes indicators for multiple symbols.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndicatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=indicator__pb2.IndicatorReq.FromString,
                    response_serializer=indicator__pb2.IndicatorResp.SerializeToString,
            ),
            'BatchCalculate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCalculate,
                    request_deserializer=indicator__pb2.BatchIndicatorReq.FromString,
                    response_serializer=indicator__pb2.BatchIndicatorResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryptohub.IndicatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cryptohub.IndicatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndicatorService(object):
    """IndicatorService calculates technical indicators.
    """

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryptohub.IndicatorService/Calculate',
            indicator__pb2.IndicatorReq.SerializeToString,
            indicator__pb2.IndicatorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCalculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryptohub.IndicatorService/BatchCalculate',
            indicator__pb2.BatchIndicatorReq.SerializeToString,
            indicator__pb2.BatchIndicatorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
