# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: indicator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'indicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0findicator.proto\x12\tcryptohub\"\x91\x01\n\x0eIndicatorParam\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\x05\x12\x33\n\x05\x65xtra\x18\x03 \x03(\x0b\x32$.cryptohub.IndicatorParam.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"n\n\x0cIndicatorReq\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12-\n\nindicators\x18\x03 \x03(\x0b\x32\x19.cryptohub.IndicatorParam\x12\r\n\x05limit\x18\x04 \x01(\x05\"\x9a\x01\n\x0eIndicatorValue\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x01\x12\x39\n\x08metadata\x18\x03 \x03(\x0b\x32\'.cryptohub.IndicatorValue.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"a\n\rIndicatorResp\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12-\n\nindicators\x18\x02 \x03(\x0b\x32\x19.cryptohub.IndicatorValue\x12\x11\n\ttimestamp\x18\x03 \x01(\t\">\n\x11\x42\x61tchIndicatorReq\x12)\n\x08requests\x18\x01 \x03(\x0b\x32\x17.cryptohub.IndicatorReq\"?\n\x12\x42\x61tchIndicatorResp\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.cryptohub.IndicatorResp2\xa1\x01\n\x10IndicatorService\x12>\n\tCalculate\x12\x17.cryptohub.IndicatorReq\x1a\x18.cryptohub.IndicatorResp\x12M\n\x0e\x42\x61tchCalculate\x12\x1c.cryptohub.BatchIndicatorReq\x1a\x1d.cryptohub.BatchIndicatorRespB7Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pb'
  _globals['_INDICATORPARAM_EXTRAENTRY']._loaded_options = None
  _globals['_INDICATORPARAM_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_INDICATORVALUE_METADATAENTRY']._loaded_options = None
  _globals['_INDICATORVALUE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INDICATORPARAM']._serialized_start=31
  _globals['_INDICATORPARAM']._serialized_end=176
  _globals['_INDICATORPARAM_EXTRAENTRY']._serialized_start=132
  _globals['_INDICATORPARAM_EXTRAENTRY']._serialized_end=176
  _globals['_INDICATORREQ']._serialized_start=178
  _globals['_INDICATORREQ']._serialized_end=288
  _globals['_INDICATORVALUE']._serialized_start=291
  _globals['_INDICATORVALUE']._serialized_end=445
  _globals['_INDICATORVALUE_METADATAENTRY']._serialized_start=398
  _globals['_INDICATORVALUE_METADATAENTRY']._serialized_end=445
  _globals['_INDICATORRESP']._serialized_start=447
  _globals['_INDICATORRESP']._serialized_end=544
  _globals['_BATCHINDICATORREQ']._serialized_start=546
  _globals['_BATCHINDICATORREQ']._serialized_end=608
  _globals['_BATCHINDICATORRESP']._serialized_start=610
  _globals['_BATCHINDICATORRESP']._serialized_end=673
  _globals['_INDICATORSERVICE']._serialized_start=676
  _globals['_INDICATORSERVICE']._serialized_end=837
# @@protoc_insertion_point(module_scope)
