# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import market_pb2 as market__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """MarketDataService provides real-time and historical market data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKlines = channel.unary_unary(
                '/cryptohub.MarketDataService/GetKlines',
                request_serializer=market__pb2.KlineReq.SerializeToString,
                response_deserializer=market__pb2.KlineResp.FromString,
                _registered_method=True)
        self.SubscribeTicker = channel.unary_stream(
                '/cryptohub.MarketDataService/SubscribeTicker',
                request_serializer=market__pb2.TickerReq.SerializeToString,
                response_deserializer=market__pb2.TickerUpdate.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """MarketDataService provides real-time and historical market data.
    """

    def GetKlines(self, request, context):
        """GetKlines returns historical candlestick data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTicker(self, request, context):
        """SubscribeTicker provides streaming ticker updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKlines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKlines,
                    request_deserializer=market__pb2.KlineReq.FromString,
                    response_serializer=market__pb2.KlineResp.SerializeToString,
            ),
            'SubscribeTicker': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTicker,
                    request_deserializer=market__pb2.TickerReq.FromString,
                    response_serializer=market__pb2.TickerUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryptohub.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cryptohub.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """MarketDataService provides real-time and historical market data.
    """

    @staticmethod
    def GetKlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryptohub.MarketDataService/GetKlines',
            market__pb2.KlineReq.SerializeToString,
            market__pb2.KlineResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTicker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cryptohub.MarketDataService/SubscribeTicker',
            market__pb2.TickerReq.SerializeToString,
            market__pb2.TickerUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
