# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'market.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\x12\tcryptohub\"a\n\x08KlineReq\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x12\n\nstart_time\x18\x04 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x03\"b\n\x05Kline\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"O\n\tKlineResp\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12 \n\x06klines\x18\x03 \x03(\x0b\x32\x10.cryptohub.Kline\"\x1c\n\tTickerReq\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"h\n\x0cTickerUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x12\n\nchange_24h\x18\x03 \x01(\x01\x12\x12\n\nvolume_24h\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x32\x8f\x01\n\x11MarketDataService\x12\x36\n\tGetKlines\x12\x13.cryptohub.KlineReq\x1a\x14.cryptohub.KlineResp\x12\x42\n\x0fSubscribeTicker\x12\x14.cryptohub.TickerReq\x1a\x17.cryptohub.TickerUpdate0\x01\x42\x37Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/louqiang1982/CryptoHub/backend/go/proto/pb'
  _globals['_KLINEREQ']._serialized_start=27
  _globals['_KLINEREQ']._serialized_end=124
  _globals['_KLINE']._serialized_start=126
  _globals['_KLINE']._serialized_end=224
  _globals['_KLINERESP']._serialized_start=226
  _globals['_KLINERESP']._serialized_end=305
  _globals['_TICKERREQ']._serialized_start=307
  _globals['_TICKERREQ']._serialized_end=335
  _globals['_TICKERUPDATE']._serialized_start=337
  _globals['_TICKERUPDATE']._serialized_end=441
  _globals['_MARKETDATASERVICE']._serialized_start=444
  _globals['_MARKETDATASERVICE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
